UserAuthentication/urls.py
from django.contrib import admin
from django.urls import path
from  UserAuthentication import views

app_name="UserAuthentication"

urlpatterns = [
    path('register', views.register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout',views.user_logout,name="logout"),
    path('reset',views.password_reset,name="reset"),
    path('confirm',views.email_confirm,name="confirm"),


]

app1/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views

app_name="app1"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('packages', views.packages, name="packages"),

    path('detailed_view/<p>', views.detailed_view, name="detailed_view"),

    # path('rating', views.rating, name="rating"),
    path('rating/<str:package_name>/', views.rating, name='rating'),

    path('thanks', views.thanks, name="thanks"),

    path('review', views.review, name="review"),

    path('about', views.about, name="about"),









]

myproject1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('auth/', include('UserAuthentication.urls')),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/userAuth/email_confirm.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    body {
        margin: 0;
        padding: 0;
        height: 100vh;
        background-image: url('{% static 'images/mou1.jpg' %}');
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        font-family: Arial, sans-serif;
    }

    .email-confirm-container {
        display: flex;
        justify-content: center; /* Center horizontally */
        align-items: center; /* Center vertically */
        height: 100vh; /* Full viewport height */
        text-align: center; /* Center text within the container */
    }

    .form-container {
    display: flex;
        background-color: rgba(255, 255, 255, 0.8);
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.8);
        max-width: 400px;
        width: 100%;
    }

    h3 {
        color: #fff;
        text-align: center;
        margin-bottom: 20px;
    }

    .form-label {
        color: #333;
        font-weight: bold;
    }

    .email-input {
        width: calc(100% - 20px);
        padding: 10px;
        border-radius: 5px;
        border: 1px solid #ccc;
        margin-bottom: 20px;
    }

    .submit-btn {
        background-color: #007bff;
        border: none;
        color: white;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .submit-btn:hover {
        background-color: #0056b3;
    }

    .message {
        color: red;
        text-align: center;
        font-weight: bold;
    }
</style>

<div class="email-confirm-container">

        <form method="POST" class="myform" data-aos="zoom-in" data-tilt>
            {% csrf_token %}
            <div>
                <label class="form-label" for="email" style="color:white";>Enter your email address:</label>
                <input type="email" id="email" name="email" class="email-input" placeholder="Your email address">
            </div>
            <button type="submit" class="submit-btn">Submit</button>
            {% if messages %}
            <div class="message">
                {% for message in messages %} <strong>
                {{ message }}
                {% endfor %}
            </div>
            {% endif %}
        </form>
    </div>
</div>

{% endblock %}

templates/userAuth/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    body {
        margin: 0;
        padding: 0;
        height: 100vh;
        background-image: url('{% static 'images/mou1.jpg' %}');
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        font-family: Arial, sans-serif;
    }

    .login-form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
    }

    .login-title, .login-label {
        color: black;
        text-align: center;
    }

    .login-form {
        background-color: rgba(255, 255, 255, 0.5);
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.8);
        max-width: 400px;
        width: 100%;
    }

    .login-form-group {
        margin-bottom: 20px;
        position: relative;
    }

    .login-input {
        width: calc(100% - 20px);
        padding: 10px;
        border-radius: 5px;
        border: 1px solid #ccc;
    }

    .eye-icon {
        position: absolute;
        top: 50%;
        right: 30px; /* Adjust as needed */
        transform: translateY(-50%);
        cursor: pointer;
    }

    .login-btn {
        background-color: #007bff;
        border: none;
        color: white;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .login-btn:hover {
        background-color: #0056b3;
    }

    .login-link {
        color: #007bff;
        text-decoration: none;
        font-size: 18px;
        font-weight: bold;
    }

    .login-link:hover {
        text-decoration: underline;
    }

    .login-message {
        color: red;
        text-align: center;
    }

    .hide {
        display: none;
    }
</style>

<div class="login-form-container">
    <form method="POST" class="login-form" data-aos="zoom-in">
        <h3 class="login-title">Login Here</h3>
        {% csrf_token %}

        <div class="login-form-group">
            <label class="login-label"><strong>Username</strong></label>
            <input type="text" class="login-input" name="u" placeholder="Enter username">
        </div>

        <div class="login-form-group">
            <label  style="position: relative; width: 360px;"><strong>Password</strong>
                <input type="password" class="login-input" id="password" name="p" placeholder="Enter password" >
                <button type="button" id="togglePassword" onclick="togglePasswordVisibility('password')" class="hide-eye" style="position: absolute; top: 70%; right: 20px; transform: translateY(-50%); background: none; border: none;"><i class="fas fa-eye" style="color: #999;"></i></button>


            </label>
        </div>

        <div class="login-form-group">
            <center>
                <input type="submit" class="login-btn" value="Login">
            </center>
        </div>

        <div class="login-form-group">
            <center>
                <a href="{% url 'UserAuthentication:confirm' %}" class="login-link" style="color:black;">Forgot Password?</a>
                <span style="margin: 0 10px;"> | </span>
                <a href="{% url 'UserAuthentication:register' %}" class="login-link" style="color:black;">Register</a>
            </center>
        </div>

        <div class="login-message">
            {% if messages %}
                <ul>
                    {% for msg in messages %}
                        <li>{{ msg }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </form>
</div>

<script>
    document.getElementById('togglePassword').addEventListener('click', function () {
        var passwordInput = document.getElementById('password');
        var eyeIcon = document.getElementById('togglePassword');

        if (passwordInput.type === 'password') {
            passwordInput.type = 'text';
            eyeIcon.innerHTML = '<i class="fas fa-eye-slash" style="color: #999;"></i>';
        } else {
            passwordInput.type = 'password';
            eyeIcon.innerHTML = '<i class="fas fa-eye" style="color: #999;"></i>';
        }
    });
</script>

{% endblock %}

templates/userAuth/password_reset.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    body {
        margin: 0;
        padding: 0;
        height: 100vh;
        background-image: url('{% static 'images/mou1.jpg' %}');
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        font-family: Arial, sans-serif;
    }

    .form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
    }

    .myform {
        box-shadow: 0 0 10px rgba(0, 0, 0, 9.1);
        width: 400px;
    }

    .myform label {
        margin-bottom: 10px;
        display: block;
        font-weight: bold;
        width: 150px;
    }

    .input-container {
        display: flex;
        align-items: center;
    }

    .error-message {
        color: red;
        margin-top: 5px;
    }

    .myform {
    background-color: rgba(255, 255, 255, .8);
    }
</style>

<body>

<div class="form-container">
    <form method="POST" class="myform" data-aos="zoom-in" data-tilt>
        <center>
            <h3 ><strong>Reset your password</h3>
        </center>
        {% csrf_token %}


        <div class="mb-3" style="display: flex;">
            <label class="register-form-label" style="flex: 1; text-align: right; margin-right: 10px; margin-top: 20px ">Enter OTP:</label>
            <div style="flex: 2; position: relative;">
            <input type="text" id="otp" class="register-form-control" name="otp" style="width: 100%; margin-top: 20px">
            </div>
        </div>

        {% if messages %}
        <div class="error-message" style="margin:10px;">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </div>
        {% endif %}


         <div class="mb-3" style="display: flex;">
            <label class="register-form-label" style="flex: 1; text-align: right; margin-right: 10px; ">Password:</label>
            <div style="flex: 2; position: relative;">
                <input type="password" class="register-form-control" id="password" name="new_password" placeholder="Enter your password" style="width: 100%;">
                <button type="button" id="togglePassword" onclick="togglePasswordVisibility('password')" style="position: absolute; top: 50%; right: 5px; transform: translateY(-50%); background: none; border: none;"><i class="fas fa-eye" style="color: #999;"></i></button>
            </div>
        </div>

        <div class="mb-3" style="display: flex;">
            <label class="register-form-label" style="flex: 1; text-align: right; margin-right: 10px; ">Confirm Password:</label>
            <div style="flex: 2; position: relative;">
                <input type="password" class="register-form-control" id="confirmPassword" name="confirm_password" placeholder="Confirm your password" style="width: 100%;">
                <button type="button" id="toggleConfirmPassword" onclick="togglePasswordVisibility('confirmPassword')" style="position: absolute; top: 50%; right: 5px; transform: translateY(-50%); background: none; border: none;"><i class="fas fa-eye" style="color: #999;"></i></button>
            </div>
        </div>
        <center>
            <button type="submit" style="padding: 3px 10px" class="attractive-btn ">Submit</button>
        </center>
    </form>
</div>

<script>
    function togglePasswordVisibility(inputId) {
        var passwordInput = document.getElementById(inputId);
        var toggleButton = document.getElementById('toggle' + inputId.charAt(0).toUpperCase() + inputId.slice(1));

        if (passwordInput.type === "password") {
            passwordInput.type = "text";
            toggleButton.innerHTML = '<i class="fas fa-eye-slash"></i>';
        } else {
            passwordInput.type = "password";
            toggleButton.innerHTML = '<i class="fas fa-eye"></i>';
        }
    }
</script>


</body>

{% endblock %}

templates/userAuth/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    body {
        margin: 0;
        padding: 0;
        height: 100vh;
        background-image: url('{% static 'images/mou1.jpg' %}');
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        font-family: Arial, sans-serif;
    }
</style>

<body>

<center>
    <div class="register-form-container">
        <div class="form-container">
            <form method="POST" class="register-myform" onsubmit="showSuccessAlert()" data-aos="zoom-in">
                <center><h3>Register here</h3></center>
                {% csrf_token %}

                <div style="margin:10px;">
                    <div class="mb-3" style="display: flex;">
                        <label class="register-form-label" style="flex: 1; text-align: right; margin-right: 10px;">Username:</label>
                        <input type="text" class="register-form-control" name="u" style="flex: 2;" placeholder="Enter your username">
                    </div>

                    <div class="mb-3" style="display: flex;">
                        <label class="register-form-label" style="flex: 1; text-align: right; margin-right: 10px;">Password:</label>
                        <div style="flex: 2; position: relative;">
                            <input type="password" class="register-form-control" id="password" name="p" placeholder="Enter your password" style="width: 100%;">
                            <button type="button" id="togglePassword" onclick="togglePasswordVisibility('password')" style="position: absolute; top: 50%; right: 5px; transform: translateY(-50%); background: none; border: none;"><i class="fas fa-eye" style="color: #999;"></i></button>
                        </div>
                    </div>

                    <div class="mb-3" style="display: flex;">
                        <label class="register-form-label" style="flex: 1; text-align: right; margin-right: 10px;">Confirm Password:</label>
                        <div style="flex: 2; position: relative;">
                            <input type="password" class="register-form-control" id="confirmPassword" name="p1" placeholder="Confirm your password" style="width: 100%;">
                            <button type="button" id="toggleConfirmPassword" onclick="togglePasswordVisibility('confirmPassword')" style="position: absolute; top: 50%; right: 5px; transform: translateY(-50%); background: none; border: none;"><i class="fas fa-eye" style="color: #999;"></i></button>
                        </div>
                    </div>

                    <div class="mb-3" style="display: flex;">
                        <label class="register-form-label" style="flex: 1;">First Name:</label>
                        <input type="text" class="register-form-control" name="f" style="flex: 2;" placeholder="Enter your first name">
                    </div>

                    <div class="mb-3" style="display: flex;">
                        <label class="register-form-label" style="flex: 1;">Last Name:</label>
                        <input type="text" class="register-form-control" name="l" style="flex: 2;" placeholder="Enter your last name">
                    </div>

                    <div class="mb-3" style="display: flex;">
                        <label class="register-form-label" style="flex: 1;">Email:</label>
                        <input type="email" class="register-form-control" name="e" style="flex: 2;" placeholder="Enter your e-mail address">
                    </div>

                    {% for message in messages %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>
                    {% endfor %}

                    <div class="mb-3" style="display: flex; justify-content: center;">
                        <input type="submit" class="register-attractive-btn" style="padding: 4px 70px;">
                    </div>

                    <div class="register-login-links">
                        <span>Already have an account?</span>
                        <a href="{% url 'UserAuthentication:login' %}" class="login-link">Login</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</center>

<script>
    function togglePasswordVisibility(inputId) {
        var passwordInput = document.getElementById(inputId);
        var toggleButton = document.getElementById('toggle' + inputId.charAt(0).toUpperCase() + inputId.slice(1));

        if (passwordInput.type === "password") {
            passwordInput.type = "text";
            toggleButton.innerHTML = '<i class="fas fa-eye-slash"></i>';
        } else {
            passwordInput.type = "password";
            toggleButton.innerHTML = '<i class="fas fa-eye"></i>';
        }
    }
</script>

</body>

{% endblock %}